version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
    ports:
      - "8081:8081"

  backend:
    build: ./back_grossiste
    container_name: backend_grossiste
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "5000:5000"
    volumes:
      - ./back_grossiste:/app
      - /app/node_modules
    command: ["npm", "start"]

volumes:
  mongodb_data:
